<?php
Am_Di::getInstance()->plugins_protect->get('wordpress')->startLayout($this, $title,true);

add_filter('thesis_custom_loop', function (){return 'am_thesis_loop';});

function am_thesis_loop(){
    print $GLOBALS['AM_THESIS_PAGE_CONTENT'];
}

ob_start();
?>    

<div style="padding:0 1em;">
    <?php 
        include dirname(__FILE__)."/../amember.php";
    ?>
    </div>

<?php 

$GLOBALS['AM_THESIS_PAGE_CONTENT'] = ob_get_clean();

thesis_html_framework();
