<?php if (!defined('AM_ADMIN') || !AM_ADMIN): ?>
    <?php if (empty($this->layoutNoLang)): ?>
        <?php include $this->_script('_lang-choice.phtml'); ?>
    <?php endif; ?>
    <?php if (empty($this->layoutNoMenu)): ?>
        <?php $user = Am_Di::getInstance()->auth->getUser(); ?>
        <?php if ($user && empty($this->noUserIdentityBlock)) : ?>
        <?php endif; ?>
        <?php if ($user) : ?>
            <?php include $this->_script('member/_menu.phtml'); ?>
        <?php endif; ?>
    <?php endif; // layoutNoMenu ?>
<?php endif; ?>
<?php include $this->_script('_msg.phtml'); ?>
<?php echo $this->blocks('member/top') ?>